services:
  backend:
    build: ./backend
    container_name: django_backend
    volumes:
      - /root/referral-task-bot/backend/static:/app/static
      - /root/referral-task-bot/backend/media:/app/media
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "127.0.0.1:8000:8000"
  bot:
    build: ./bot
    container_name: telegram_bot
    volumes:
      - ./bot:/app/bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_BASE_URL=${API_BASE_URL}
      - SUPPORT_USERNAME=${SUPPORT_USERNAME}
      - REQUIRED_CHANNEL_USERNAME=${REQUIRED_CHANNEL_USERNAME}
    depends_on:
      - backend